// click_player.ino — ItsyBitsy M4 Express (SAMD51)
//
// Dedicated click-audio player for the behaviour_bmi rig.
//
// The Raspberry Pi is the sole scheduler: it busy-waits to each Poisson
// click time and fires a 100 µs TTL HIGH pulse on BCM10 (left) or BCM9
// (right).  A RISING-edge interrupt here resets the DAC playback position
// to zero; the TC3 timer ISR at 192 kHz clocks out one 12-bit sample per
// channel each period.
//
// Pinout:
//   D9  — left  trigger input  (Pi BCM7 / physical 26)
//   D10 — right trigger input  (Pi BCM1 / physical 28)
//   A0  — left  DAC output  (through 10 µF DC-blocking cap to amplifier)
//   A1  — right DAC output  (through 10 µF DC-blocking cap to amplifier)
//
// Waveform: 4 tones (2/4/8/16 kHz), 40 dB attenuation each, cosine²
// fade-in and fade-out (2 ms each), peak-normalised, 576 samples @ 192 kHz.

#define TRIGGER_LEFT  9
#define TRIGGER_RIGHT 10

// ---------------------------------------------------------------------------
// Uncomment for timing-validation builds only — outputs a 3 ms square pulse
// on both DAC channels instead of the production waveform  so the rising edge
// is threshold-detectable on an oscilloscope.  Leave commented for production.
// ---------------------------------------------------------------------------
//#define SQUARE_PULSE_VALIDATION

// ---------------------------------------------------------------------------
// Pre-baked waveform (generated by run_once_generate_waveform.py)
// 576 samples, 12-bit unsigned, centred at 2048 = silence
// ---------------------------------------------------------------------------
#define CLICK_LEN 576
const uint16_t CLICK_WAV[CLICK_LEN] = {
  2048, 2048, 2048, 2049, 2049, 2050, 2050, 2050, 2050, 2050, 2051, 2052, 2053, 2055, 2057, 2058,
  2057, 2055, 2052, 2049, 2046, 2045, 2047, 2052, 2060, 2069, 2077, 2082, 2083, 2078, 2070, 2059,
  2048, 2040, 2036, 2036, 2041, 2046, 2048, 2046, 2037, 2021, 2002, 1985, 1974, 1973, 1987, 2013,
  2048, 2086, 2120, 2143, 2151, 2143, 2122, 2095, 2070, 2053, 2047, 2054, 2068, 2082, 2087, 2077,
  2048, 2002, 1948, 1895, 1856, 1841, 1854, 1894, 1951, 2011, 2060, 2084, 2077, 2038, 1976, 1906,
  1842, 1798, 1783, 1795, 1825, 1860, 1883, 1882, 1853, 1800, 1737, 1684, 1662, 1686, 1765, 1891,
  2048, 2212, 2354, 2455, 2500, 2491, 2441, 2374, 2314, 2284, 2292, 2338, 2405, 2470, 2508, 2499,
  2435, 2326, 2194, 2069, 1985, 1965, 2020, 2140, 2302, 2467, 2597, 2660, 2640, 2541, 2385, 2208,
  2048, 1937, 1890, 1905, 1960, 2020, 2051, 2024, 1932, 1785, 1616, 1469, 1388, 1406, 1536, 1762,
  2048, 2341, 2586, 2738, 2775, 2702, 2548, 2360, 2189, 2077, 2045, 2084, 2166, 2244, 2270, 2209,
  2048, 1806, 1525, 1264, 1083, 1025, 1108, 1312, 1591, 1877, 2102, 2210, 2174, 2005, 1742, 1449,
  1193, 1028, 980, 1041, 1174, 1320, 1418, 1424, 1324, 1138, 921, 745, 682, 784, 1069, 1511,
  2048, 2594, 3059, 3375, 3506, 3461, 3290, 3067, 2872, 2769, 2788, 2917, 3107, 3288, 3385, 3345,
  3152, 2834, 2456, 2106, 1874, 1822, 1971, 2294, 2718, 3144, 3471, 3619, 3555, 3291, 2891, 2445,
  2048, 1777, 1667, 1706, 1839, 1983, 2054, 1993, 1782, 1451, 1076, 756, 587, 640, 933, 1431,
  2048, 2670, 3180, 3489, 3554, 3390, 3065, 2678, 2331, 2106, 2041, 2119, 2277, 2425, 2472, 2352,
  2048, 1597, 1081, 611, 294, 204, 366, 742, 1243, 1750, 2141, 2326, 2264, 1975, 1535, 1052,
  637, 378, 313, 426, 652, 894, 1058, 1075, 927, 651, 332, 79, 1, 170, 605, 1263,
  2048, 2833, 3491, 3926, 4094, 4016, 3763, 3444, 3168, 3020, 3037, 3201, 3443, 3668, 3781, 3716,
  3457, 3043, 2560, 2121, 1833, 1771, 1955, 2345, 2851, 3351, 3727, 3888, 3798, 3481, 3013, 2498,
  2048, 1745, 1625, 1672, 1819, 1977, 2055, 1990, 1766, 1420, 1034, 710, 548, 612, 920, 1428,
  2048, 2663, 3159, 3451, 3503, 3335, 3016, 2642, 2313, 2102, 2042, 2113, 2256, 2388, 2427, 2318,
  2048, 1653, 1209, 811, 550, 485, 634, 958, 1382, 1803, 2124, 2273, 2221, 1990, 1643, 1267,
  951, 759, 720, 817, 996, 1185, 1314, 1332, 1230, 1037, 816, 646, 602, 732, 1045, 1507,
  2048, 2581, 3019, 3301, 3403, 3340, 3166, 2950, 2766, 2666, 2672, 2769, 2914, 3046, 3107, 3059,
  2895, 2641, 2351, 2091, 1923, 1888, 1995, 2217, 2501, 2777, 2979, 3060, 3003, 2824, 2566, 2288,
  2048, 1889, 1828, 1854, 1931, 2012, 2051, 2019, 1908, 1740, 1554, 1402, 1329, 1366, 1516, 1758,
  2048, 2331, 2554, 2682, 2700, 2620, 2474, 2308, 2163, 2071, 2045, 2075, 2135, 2189, 2204, 2158,
  2048, 1890, 1716, 1562, 1465, 1445, 1507, 1635, 1798, 1957, 2076, 2130, 2110, 2027, 1905, 1774,
  1667, 1605, 1596, 1633, 1697, 1763, 1808, 1817, 1786, 1728, 1662, 1614, 1605, 1649, 1747, 1888,
  2048, 2202, 2326, 2402, 2426, 2405, 2352, 2291, 2239, 2210, 2209, 2232, 2266, 2296, 2307, 2292,
  2249, 2187, 2118, 2058, 2020, 2013, 2036, 2084, 2143, 2198, 2236, 2249, 2234, 2197, 2145, 2092,
  2048, 2020, 2010, 2015, 2029, 2042, 2049, 2043, 2027, 2002, 1976, 1957, 1949, 1957, 1979, 2011,
  2048, 2082, 2107, 2119, 2119, 2108, 2092, 2074, 2059, 2050, 2048, 2050, 2055, 2059, 2060, 2056,
  2048, 2038, 2027, 2020, 2016, 2017, 2021, 2029, 2037, 2044, 2049, 2051, 2050, 2047, 2044, 2041,
  2040, 2039, 2040, 2042, 2043, 2045, 2046, 2046, 2046, 2046, 2047, 2047, 2047, 2048, 2048, 2048,
};

// ---------------------------------------------------------------------------
// Playback state — written by trigger ISR, read by timer ISR.
// Cortex-M4 16-bit aligned loads/stores are atomic → no mutex needed.
// CLICK_LEN or greater means idle (DAC outputs silence).
// ---------------------------------------------------------------------------
volatile uint16_t pos_left  = CLICK_LEN;
volatile uint16_t pos_right = CLICK_LEN;

// ---------------------------------------------------------------------------
// Trigger ISRs — reset playback position on RISING edge
// ---------------------------------------------------------------------------
void onLeftTrigger()  { pos_left  = 0; }
void onRightTrigger() { pos_right = 0; }

// ---------------------------------------------------------------------------
// TC3 timer ISR — fires at 192 kHz (120 MHz / 625)
// Outputs one 12-bit DAC sample per channel per period.
// ---------------------------------------------------------------------------
void TC3_Handler() {
    TC3->COUNT16.INTFLAG.bit.MC0 = 1;  // clear Match/Compare 0 flag

    uint16_t pl = pos_left;
    uint16_t pr = pos_right;

    // SAMD51: must wait for previous conversion to finish before writing DATA[n].
    // At 192 kHz the DAC is nearly always ready; the loop rarely iterates.
    while (DAC->SYNCBUSY.bit.DATA0);
#ifdef SQUARE_PULSE_VALIDATION
    DAC->DATA[0].reg = (pl < CLICK_LEN) ? 4095 : 2048;
#else
    DAC->DATA[0].reg = (pl < CLICK_LEN) ? CLICK_WAV[pl] : 2048;
#endif
    while (DAC->SYNCBUSY.bit.DATA1);
#ifdef SQUARE_PULSE_VALIDATION
    DAC->DATA[1].reg = (pr < CLICK_LEN) ? 4095 : 2048;
#else
    DAC->DATA[1].reg = (pr < CLICK_LEN) ? CLICK_WAV[pr] : 2048;
#endif

    if (pl < CLICK_LEN) pos_left  = pl + 1;
    if (pr < CLICK_LEN) pos_right = pr + 1;
}

// ---------------------------------------------------------------------------
// TC3 setup — 16-bit Match-Frequency mode, no prescaler, period = 624
// GCLK0 = 120 MHz → 120 000 000 / 625 = 192 000 Hz
// ---------------------------------------------------------------------------
static void setup_tc3_192kHz() {
    // Open the APB peripheral bus clock for TC3.  GCLK routing alone is not
    // enough on SAMD51 — the MCLK gate must also be set.  This is idempotent
    // if the Arduino core already enabled it (e.g. for PWM on this pin).
    MCLK->APBBMASK.reg |= MCLK_APBBMASK_TC3;

    // Route GCLK0 (120 MHz) to TC3 (SAMD51 uses per-peripheral PCHCTRL with TC3_GCLK_ID)
    GCLK->PCHCTRL[TC3_GCLK_ID].reg = GCLK_PCHCTRL_GEN_GCLK0 | GCLK_PCHCTRL_CHEN;
    while (!GCLK->PCHCTRL[TC3_GCLK_ID].bit.CHEN);

    // Software reset
    TC3->COUNT16.CTRLA.bit.SWRST = 1;
    while (TC3->COUNT16.SYNCBUSY.bit.SWRST);

    // 16-bit mode, no prescaler (SAMD51: WAVEGEN moved to separate WAVE register)
    TC3->COUNT16.CTRLA.reg = TC_CTRLA_MODE_COUNT16 | TC_CTRLA_PRESCALER_DIV1;
    TC3->COUNT16.WAVE.reg  = TC_WAVE_WAVEGEN_MFRQ;  // counter resets to 0 at CC[0]
    TC3->COUNT16.CC[0].reg = 624;   // period = 625 counts = 192 kHz
    while (TC3->COUNT16.SYNCBUSY.bit.CC0);

    // Enable Match/Compare 0 interrupt at highest hardware priority
    TC3->COUNT16.INTENSET.bit.MC0 = 1;
    NVIC_SetPriority(TC3_IRQn, 0);
    NVIC_EnableIRQ(TC3_IRQn);

    // Enable the timer
    TC3->COUNT16.CTRLA.bit.ENABLE = 1;
    while (TC3->COUNT16.SYNCBUSY.bit.ENABLE);
}

// ---------------------------------------------------------------------------
void setup() {
    // Enable both 12-bit DAC channels and set them to mid-rail (silence).
    // analogWrite initialises the DAC peripheral; subsequent writes in the
    // ISR go directly to DAC->DATA[n].reg for lowest latency.
    analogWriteResolution(12);
    analogWrite(A0, 2048);
    analogWrite(A1, 2048);

    // Force VDDANA (3.3 V) as DAC reference — analogWrite() may leave it on
    // the internal bandgap (~1.2 V), which would cap peak output at ~1.2 V.
    while (DAC->SYNCBUSY.bit.SWRST || DAC->SYNCBUSY.bit.ENABLE);
    DAC->CTRLB.bit.REFSEL = 0x02;  // VDDANA on SAMD51

    setup_tc3_192kHz();

    pinMode(TRIGGER_LEFT,  INPUT);
    pinMode(TRIGGER_RIGHT, INPUT);
    attachInterrupt(digitalPinToInterrupt(TRIGGER_LEFT),  onLeftTrigger,  RISING);
    attachInterrupt(digitalPinToInterrupt(TRIGGER_RIGHT), onRightTrigger, RISING);
}

void loop() {
    // Everything is interrupt-driven — nothing to do here.
}
