"""
Action registry for the trial state machine engine.

Each entry in ACTIONS maps a JSON action "type" string to a Python function.
All hardware interaction goes exclusively through gpio_handler.
"""

import ctypes
import logging
import threading
import time

import gpio_handler
from config import LED_PINS, VALVE_PINS, AUDIO_PINS, CLICK_PULSE_US

logger = logging.getLogger(__name__)


def _set_rt_priority(priority: int = 80) -> None:
    """Elevate the calling thread to SCHED_FIFO.  Requires root / CAP_SYS_NICE."""
    SCHED_FIFO = 1
    class _Param(ctypes.Structure):
        _fields_ = [("sched_priority", ctypes.c_int)]
    ret = ctypes.CDLL("libc.so.6").sched_setscheduler(0, SCHED_FIFO, ctypes.byref(_Param(priority)))
    if ret != 0:
        logger.warning("SCHED_FIFO unavailable — run as root for best click timing")


def _led_on(target: str) -> None:
    gpio_handler.set_led(target, True)


def _led_off(target: str) -> None:
    gpio_handler.set_led(target, False)


def _valve_open(target: str) -> None:
    gpio_handler.set_valve(target, True)


def _valve_close(target: str) -> None:
    gpio_handler.set_valve(target, False)


# ---------------------------------------------------------------------------
# Click trigger output — ItsyBitsy M4 TTL path
#
# The Pi busy-waits to each scheduled click time and fires a short TTL pulse
# on AUDIO_PINS["left"] (BCM10) or AUDIO_PINS["right"] (BCM9).  The
# ItsyBitsy M4 detects the RISING edge and immediately starts playing its
# pre-baked 192 kHz waveform from its onboard DAC.
# ---------------------------------------------------------------------------

# Module-level stop event; replaced atomically on each _fire_click_triggers() call.
_click_stop: threading.Event = threading.Event()
_click_stop.set()


def _fire_click_triggers(left_clicks: list, right_clicks: list,
                          on_complete=None, log_cb=None, latency_cb=None) -> None:
    """
    Busy-wait to each scheduled click time and fire a 100 µs TTL pulse on
    the corresponding AUDIO_PIN to trigger the ItsyBitsy M4 DAC.

    left_clicks / right_clicks: lists of float seconds relative to call time,
    as generated by click_generator.py and transmitted in the trial JSON.
    """
    global _click_stop
    _click_stop.set()
    _click_stop = threading.Event()
    stop = _click_stop

    if log_cb:
        log_cb("clicks", True)

    t_scheduled = time.clock_gettime(time.CLOCK_MONOTONIC)

    def _player():
        _set_rt_priority(85)

        t_buffer = time.clock_gettime(time.CLOCK_MONOTONIC)
        if latency_cb is not None:
            latency_cb(t_scheduled, t_buffer)

        t0 = time.clock_gettime(time.CLOCK_MONOTONIC)

        # Merge left and right into a single sorted sequence of (abs_time, channel)
        events = ([(t0 + t, "left")  for t in (left_clicks  or [])] +
                  [(t0 + t, "right") for t in (right_clicks or [])])
        events.sort()

        pulse_s = CLICK_PULSE_US * 1e-6

        for abs_t, ch in events:
            if stop.is_set():
                break
            # Busy-wait until the scheduled click time
            while time.clock_gettime(time.CLOCK_MONOTONIC) < abs_t:
                pass
            gpio_handler.set_audio(ch, True)
            deadline = abs_t + pulse_s
            while time.clock_gettime(time.CLOCK_MONOTONIC) < deadline:
                pass
            gpio_handler.set_audio(ch, False)

        if not stop.is_set() and on_complete is not None:
            logger.info("Click triggers done — firing on_complete")
            on_complete()

    threading.Thread(target=_player, daemon=True, name="clicks-trigger").start()
    logger.info("Click triggers started: %d left, %d right",
                len(left_clicks or []), len(right_clicks or []))


def stop_clicks() -> None:
    """Interrupt any in-progress click trigger sequence immediately."""
    _click_stop.set()
    logger.debug("Click triggers stopped")


ACTIONS: dict = {
    "led_on":      _led_on,
    "led_off":     _led_off,
    "valve_open":  _valve_open,
    "valve_close": _valve_close,
    "play_clicks": _fire_click_triggers,
}


def dispatch(action_dict: dict, on_complete=None, log_cb=None, latency_cb=None) -> None:
    """
    Look up the action type, pass remaining fields as kwargs, and execute it.
    on_complete, log_cb, and latency_cb are forwarded only for play_clicks.
    """
    action_dict = dict(action_dict)
    action_type = action_dict.pop("type", None)

    if action_type is None:
        logger.error("Action dict missing 'type' key: %s", action_dict)
        return

    fn = ACTIONS.get(action_type)
    if fn is None:
        logger.error("Unknown action type '%s' — skipping", action_type)
        return

    if action_type == "play_clicks":
        if on_complete is not None:
            action_dict["on_complete"] = on_complete
        if log_cb is not None:
            action_dict["log_cb"] = log_cb
        if latency_cb is not None:
            action_dict["latency_cb"] = latency_cb

    try:
        logger.debug("Action  %s  %s", action_type, action_dict)
        fn(**action_dict)
    except TypeError as e:
        logger.error("Bad arguments for action '%s': %s", action_type, e)
    except Exception as e:
        logger.error("Action '%s' raised an unexpected error: %s", action_type, e)


def safety_sweep() -> None:
    """Force all LEDs and valves off; call on trial abort, watchdog, or shutdown."""
    for target in LED_PINS:
        gpio_handler.set_led(target, False)
    for target in VALVE_PINS:
        gpio_handler.set_valve(target, False)
    logger.info("actions.safety_sweep complete")
