"""
Broadband click waveform builder for auditory decision tasks.

build_click()             — single 3 ms click (float32 mono array)
build_buffer_from_times() — stereo float32 buffer from pre-computed click times

Click design (matches Brody-lab spec):
  4 pure tones summed (2/4/8/16 kHz), 40 dB attenuation, cosine² fade in/out.
  Peak-normalised to ±1.0 so sounddevice writes at full DAC range.
"""

import numpy as np

SRATE  = 48_000
WIDTH  = 0.003          # seconds — click duration
RAMP   = 0.002          # seconds — cosine² taper on each end
TONES  = [2000, 4000, 8000, 16000]
ATT_DB = 40


def build_click(srate: int = SRATE, width: float = WIDTH, ramp: float = RAMP,
                tones: list = TONES, att_db: float = ATT_DB) -> np.ndarray:
    """Return a float32 mono click waveform, peak-normalised to ±1.0."""
    t   = np.arange(0, width + 1 / srate, 1 / srate)
    amp = 10 ** (-att_db / 20)

    snd = np.zeros(len(t), dtype=np.float64)
    for f in tones:
        snd += amp * np.sin(2 * np.pi * f * t)

    ramp_t = np.arange(0, ramp + 1 / srate, 1 / srate)
    edge   = np.cos(ramp_t * np.pi / (2 * ramp)) ** 2
    n      = len(edge)
    snd[:n]  *= edge[::-1]
    snd[-n:] *= edge

    peak = np.max(np.abs(snd))
    if peak > 0:
        snd /= peak

    return snd.astype(np.float32)


def build_buffer_from_times(click: np.ndarray,
                             left_times: list,
                             right_times: list,
                             srate: int = SRATE) -> np.ndarray:
    """
    Build a stereo (N, 2) float32 buffer from pre-computed click timestamps.

    left_times / right_times: lists of float seconds, as generated by
    click_generator.py on the PC side and transmitted in the trial JSON.
    """
    all_times = list(left_times or []) + list(right_times or [])
    if not all_times:
        return np.zeros((srate, 2), dtype=np.float32)   # 1 s silence fallback

    duration  = max(all_times) + WIDTH + 0.02           # 20 ms tail
    n_samples = int(duration * srate)
    click_len = len(click)
    buf = np.zeros((n_samples, 2), dtype=np.float32)

    for t in (left_times or []):
        i   = int(t * srate)
        end = min(i + click_len, n_samples)
        buf[i:end, 0] += click[:end - i]

    for t in (right_times or []):
        i   = int(t * srate)
        end = min(i + click_len, n_samples)
        buf[i:end, 1] += click[:end - i]

    np.clip(buf, -1.0, 1.0, out=buf)
    return buf
